project:
  type: website

website:
  title: "A data + code blog and assorted notes"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/khalido
      - icon: twitter
        href: https://twitter.com/KO
format:
  html:
    theme: flatly
    css: styles.css

execute:
  freeze: auto

